api_platform:
    title: 'BilemoApi'
    description: 'An API rest for the company Bilemo, you can view all phones in this api referenced by clients. Use "Bearer MY_NEW_TOKEN" for generate token.'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    collection:
        pagination:
            items_per_page: 5

    http_cache:
        invalidation:
            enabled: true
        #            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization', 'Origin']
        public: true
